#include <stdint.h>

#ifndef KEY_DEF_H
#define KEY_DEF_H

#define MAP(l, f) l(f)
#define KEY_LIST(f) \
        f(0) f(1) f(2) f(3) f(4) f(5) f(6) f(7) f(8) f(9) \
        f(A) f(B) f(C) f(D) f(E) f(F) f(G) f(H) f(I) f(J) \
        f(K) f(L) f(M) f(N) f(O) f(P) f(Q) f(R) f(S) f(T) \
        f(U) f(V) f(W) f(X) f(Y) f(Z) f(MINUS) f(EQ) f(LEFTBRACKET) \
        f(RIGHTBRACKET) f(BACKSLASH) f(SEMICOLON) f(APOSTROPHE) \
        f(COMMA) f(PERIOD) f(SLASH) f(SPACE) f(GRAVE) f(TAB) \
        f(ESC) f(F1) f(F2) f(F3) f(F4) f(F5) f(F6) f(F7) f(F8) \
        f(F9) f(F10) f(F11) f(F12) f(BACKSPACE) f(CAPSLOCK) f(RETURN) \
        f(LSIFHT) f(LCTRL) f(LGUI) f(LALT) f(RALT) f(RGUI) f(FN) f(RCTRL) f(RSHIFT) \
        f(UP) f(DOWN) f(LEFT) f(RIGHT) f(INSERT) f(DELETE) \
        f(HOME) f(END) f(PAGEUP) f(PAGEDOWN) f(NUM) f(KP_SLASH) f(KP_STAR) \
        f(KP_MINUS) f(KP_PLUS) f(KP_EN) f(KP) f(KP_0) f(KP_1) f(KP_2) f(KP_3) \
        f(KP_4) f(KP_5) f(KP_6) f(KP_7) f(KP_8) f(KP_9)  

#define DEF_KEY_ID(name) _KEY_ ## name, 
enum {_KEY_NONE, MAP(KEY_LIST, DEF_KEY_ID) NR_KEY};

uint8_t keycode2key_id[132] = {
    [0x01] = _KEY_F9,
    [0x03] = _KEY_F5,
    [0x04] = _KEY_F3,
    [0x05] = _KEY_F1,
    [0x06] = _KEY_F2,
    [0x07] = _KEY_F12,
    [0x09] = _KEY_F10,
    [0x0a] = _KEY_F8,
    [0x0b] = _KEY_F6,
    [0x0c] = _KEY_F4,
    [0x0d] = _KEY_TAB,
    [0x0e] = _KEY_GRAVE,
    [0x11] = _KEY_LALT,
    [0x12] = _KEY_LSIFHT,
    [0x14] = _KEY_LCTRL,
    [0x15] = _KEY_Q,
    [0x16] = _KEY_1,
    [0x1a] = _KEY_Z,
    [0x1b] = _KEY_S,
    [0x1c] = _KEY_A,
    [0x1d] = _KEY_W,
    [0x1e] = _KEY_2,
    [0x21] = _KEY_C,
    [0x22] = _KEY_X,
    [0x23] = _KEY_D,
    [0x24] = _KEY_E,
    [0x25] = _KEY_4,
    [0x26] = _KEY_3,
    [0x29] = _KEY_SPACE,
    [0x2a] = _KEY_V,
    [0x2b] = _KEY_F,
    [0x2c] = _KEY_T,
    [0x2d] = _KEY_R,
    [0x2e] = _KEY_5,
    [0x31] = _KEY_N,
    [0x32] = _KEY_B,
    [0x33] = _KEY_H,
    [0x34] = _KEY_G,
    [0x35] = _KEY_Y,
    [0x36] = _KEY_6,
    [0x3a] = _KEY_M,
    [0x3b] = _KEY_J,
    [0x3c] = _KEY_U,
    [0x3d] = _KEY_7,
    [0x3e] = _KEY_8,
    [0x41] = _KEY_COMMA,
    [0x42] = _KEY_K,
    [0x43] = _KEY_I,
    [0x44] = _KEY_O,
    [0x45] = _KEY_0,
    [0x46] = _KEY_9,
    [0x49] = _KEY_PERIOD,
    [0x4a] = _KEY_SLASH,
    [0x4b] = _KEY_L,
    [0x4c] = _KEY_SEMICOLON,
    [0x4d] = _KEY_P,
    [0x4e] = _KEY_MINUS,
    [0x52] = _KEY_APOSTROPHE,
    [0x54] = _KEY_LEFTBRACKET,
    [0x55] = _KEY_EQ,
    [0x58] = _KEY_CAPSLOCK,
    [0x59] = _KEY_RSHIFT,
    [0x5a] = _KEY_RETURN,
    [0x5b] = _KEY_RIGHTBRACKET,
    [0x5d] = _KEY_BACKSLASH,
    [0x66] = _KEY_BACKSPACE,
    [0x69] = _KEY_KP_1,
    [0x6b] = _KEY_KP_4,
    [0x6c] = _KEY_KP_7,
    [0x70] = _KEY_KP_0,
    [0x71] = _KEY_KP,
    [0x72] = _KEY_KP_2,
    [0x73] = _KEY_KP_5,
    [0x74] = _KEY_KP_6,
    [0x75] = _KEY_KP_8,
    [0x76] = _KEY_ESC,
    [0x77] = _KEY_NUM,
    [0x78] = _KEY_F11,
    [0x79] = _KEY_KP_PLUS,
    [0x7a] = _KEY_KP_3,
    [0x7b] = _KEY_KP_MINUS,
    [0x7c] = _KEY_KP_STAR,
    [0x7d] = _KEY_KP_9,
    [0x83] = _KEY_F7,
};

char key_id2ascii[NR_KEY] = {
    [_KEY_0] = '0',
    [_KEY_1] = '1',
    [_KEY_2] = '2',
    [_KEY_3] = '3',
    [_KEY_4] = '4',
    [_KEY_5] = '5',
    [_KEY_6] = '6',
    [_KEY_7] = '7',
    [_KEY_8] = '8',
    [_KEY_9] = '9',
    [_KEY_A] = 'a',
    [_KEY_B] = 'b',
    [_KEY_C] = 'c',
    [_KEY_D] = 'd',
    [_KEY_E] = 'e',
    [_KEY_F] = 'f',
    [_KEY_G] = 'g',
    [_KEY_H] = 'h',
    [_KEY_I] = 'i',
    [_KEY_J] = 'j',
    [_KEY_K] = 'k',
    [_KEY_L] = 'l',
    [_KEY_M] = 'm',
    [_KEY_N] = 'n',
    [_KEY_O] = 'o',
    [_KEY_P] = 'p',
    [_KEY_Q] = 'q',
    [_KEY_R] = 'r',
    [_KEY_S] = 's',
    [_KEY_T] = 't',
    [_KEY_U] = 'u',
    [_KEY_V] = 'v',
    [_KEY_W] = 'w',
    [_KEY_X] = 'x',
    [_KEY_Y] = 'y',
    [_KEY_Z] = 'z',
    [_KEY_MINUS] = '-',
    [_KEY_EQ] = '=',
    [_KEY_LEFTBRACKET] = '[',
    [_KEY_CAPSLOCK] = 20,
    [_KEY_RETURN] = 10,
    [_KEY_RIGHTBRACKET] = ']',
    [_KEY_BACKSLASH] = '\\',
    [_KEY_BACKSPACE] = 8,
    [_KEY_SEMICOLON] = ';',
    [_KEY_APOSTROPHE] = '\'',
    [_KEY_COMMA] = ',',
    [_KEY_PERIOD] = '.',
    [_KEY_SLASH] = '/',
    [_KEY_SPACE] = ' ',
    [_KEY_GRAVE] = '`',
    [_KEY_TAB] = '\t',
};

char key_id2ascii_shift[NR_KEY] = {
    [_KEY_1] = '!',
    [_KEY_2] = '@',
    [_KEY_3] = '#',
    [_KEY_4] = '$',
    [_KEY_5] = '%',
    [_KEY_6] = '^',
    [_KEY_7] = '&',
    [_KEY_8] = '*',
    [_KEY_9] = '(',
    [_KEY_0] = ')',
    [_KEY_A] = 'A',
    [_KEY_B] = 'B',
    [_KEY_C] = 'C',
    [_KEY_D] = 'D',
    [_KEY_E] = 'E',
    [_KEY_F] = 'F',
    [_KEY_G] = 'G',
    [_KEY_H] = 'H',
    [_KEY_I] = 'I',
    [_KEY_J] = 'J',
    [_KEY_K] = 'K',
    [_KEY_L] = 'L',
    [_KEY_M] = 'M',
    [_KEY_N] = 'N',
    [_KEY_O] = 'O',
    [_KEY_P] = 'P',
    [_KEY_Q] = 'Q',
    [_KEY_R] = 'R',
    [_KEY_S] = 'S',
    [_KEY_T] = 'T',
    [_KEY_U] = 'U',
    [_KEY_V] = 'V',
    [_KEY_W] = 'W',
    [_KEY_X] = 'X',
    [_KEY_Y] = 'Y',
    [_KEY_Z] = 'Z',
    [_KEY_MINUS] = '_',
    [_KEY_EQ] = '+',
    [_KEY_LEFTBRACKET] = '{',
    [_KEY_CAPSLOCK] = 20,
    [_KEY_RETURN] = 10,
    [_KEY_RIGHTBRACKET] = '}',
    [_KEY_BACKSLASH] = '|',
    [_KEY_BACKSPACE] = 8,
    [_KEY_SEMICOLON] = ':',
    [_KEY_APOSTROPHE] = '"',
    [_KEY_COMMA] = '<',
    [_KEY_PERIOD] = '>',
    [_KEY_SLASH] = '?',
    [_KEY_SPACE] = ' ',
    [_KEY_GRAVE] = '~',
    [_KEY_TAB] = '\t',
};

#endif